version: "3"
services: 
  app:
    build: 
      context: ./
    privileged: true
    volumes:
      - "./:/usr/share/nginx/html"
      - "./node_modules:/usr/share/nginx/html/node_modules"
    ports:
      - 3033:3000
    container_name: "bookList_front_develop"
    tty: true
    networks:
      - docker_default
  mock:
    image: stoplight/prism:3.1.1
    volumes:
      - ./swagger/swagger.yml:/swagger.yml
    ports:
      - 38080:4010
    command: 'mock -h 0.0.0.0 /swagger.yml'
networks:
    docker_default:
        external: true
