openapi: 3.0.0
info:
  title: booklist
  version: '1.0'
  description: book list apis
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/user:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  id:
                    type: integer
    parameters: []
  /v1/book:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/book.v1.yaml
  /v1/note:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/note.v1.yaml
    parameters: []
  /v1/note/show:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: '1'
                  note:
                    type: string
                    example: note
                  created_at:
                    type: string
                    example: 2019/01/01
                  updated_at:
                    type: string
                    example: 2019/01/01
                  book_id:
                    type: integer
                    example: '1'
                  title:
                    type: string
                    example: title
components:
  schemas: {}
